ports:
  - port: 8080
    onOpen: open-preview
tasks:
  - before: cd complete
    init: ./gradlew clean build
    command: >
      code complete/src/main/java/hello/HelloController.java &&
      ./gradlew bootRun
github:
  prebuilds:
      pullRequestsFromForks: true